In [4]:
import pandas as pd
name_list=['a','b','c']
ages = [20,30,28]
talls = [168,175,183]
df = pd.DataFrame(data={"name": name_list, "age": ages, 'tall' : talls})
df


name  age  tall
0    a   20   168
1    b   30   175
2    c   28   183

In [8]:
import numpy as np
data = np.array([0,1,1,2,3,3,3,3,5])
print('unique',np.unique(data))

unique [0 1 2 3 5]


In [50]:
import numpy as np
import os
os.environ['TF_CPP_MIN_LOG_LEVEL']='2'
import tensorflow as tf

x = [[1,2,3],[4,5,6],[7,8,9]]
x = np.array(x)
print('x:\n',x)
x = tf.reshape(tf.convert_to_tensor(x, dtype=tf.float32),[1,3,3,1])

kernel = [[1,0,0],[0,1,0],[0,0,1]]
kernel = np.array(kernel)
print('kernel:\n',kernel)
kernel = tf.reshape(tf.convert_to_tensor(kernel, dtype=tf.float32),[3,3,1,1])


x:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
kernel:
 [[1 0 0]
 [0 1 0]
 [0 0 1]]


In [51]:
x_padding = [[1,0,2,0,3],[0,0,0,0,0],[4,0,5,0,6],[0,0,0,0,0],[7,0,8,0,9]]
x_padding = np.array(x_padding)
print(x_padding)
x_padding = x_padding.reshape(1,5,5,1)

[[1 0 2 0 3]
 [0 0 0 0 0]
 [4 0 5 0 6]
 [0 0 0 0 0]
 [7 0 8 0 9]]


In [52]:

transpose_conv = tf.nn.conv2d_transpose(input=x, 
                                        filters=kernel, 
                                        output_shape=[1,5,5,1], 
                                        strides=2, 
                                        padding='SAME')
result = transpose_conv.numpy().reshape(5,5)
print(result)

[[ 1.  0.  2.  0.  3.]
 [ 0.  6.  0.  8.  0.]
 [ 4.  0.  5.  0.  6.]
 [ 0. 12.  0. 14.  0.]
 [ 7.  0.  8.  0.  9.]]


In [53]:
conv = tf.nn.conv2d(input=x_padding, 
                    filters=kernel, 
                    strides=1, 
                    padding='SAME')
result = conv.numpy().reshape(5,5)
print(result)

[[ 1.  0.  2.  0.  3.]
 [ 0.  6.  0.  8.  0.]
 [ 4.  0.  5.  0.  6.]
 [ 0. 12.  0. 14.  0.]
 [ 7.  0.  8.  0.  9.]]


In [41]:
conv = tf.nn.conv2d(input=x_padding, 
                    filters=kernel, 
                    strides=1, 
                    padding='SAME')
result = conv.numpy().reshape(5,5)
print(result)

transpose_conv = tf.nn.conv2d_transpose(input=conv, 
                                        filters=kernel, 
                                        output_shape=[1,5,5,1], 
                                        strides=1, 
                                        padding='SAME')
result = transpose_conv.numpy().reshape(5,5)
print(result)

[[ 1.  0.  2.  0.  3.]
 [ 0.  6.  0.  8.  0.]
 [ 4.  0.  5.  0.  6.]
 [ 0. 12.  0. 14.  0.]
 [ 7.  0.  8.  0.  9.]]
[[ 7.  0. 10.  0.  3.]
 [ 0. 12.  0. 16.  0.]
 [16.  0. 25.  0. 14.]
 [ 0. 24.  0. 28.  0.]
 [ 7.  0. 20.  0. 23.]]
